steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_GCP_PROJECT_ID}/backend:${_COMMIT_SHA}', '.']
    id: Build

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_GCP_PROJECT_ID}/backend:${_COMMIT_SHA}']
    id: Push

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - backend
      - --image=gcr.io/${_GCP_PROJECT_ID}/backend:${_COMMIT_SHA}
      - --region=us
      - --platform=managed
      - --allow-unauthenticated # Jika ingin publik
      - --port=4000
    id: Deploy
    env:
      - 'PORT=4000'

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'gcr.io/${_GCP_PROJECT_ID}/backend:${_COMMIT_SHA}'

substitutions:
  _GCP_PROJECT_ID: 'g-04-450802'
  _COMMIT_SHA: 'v2'
