steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_GCP_PROJECT_ID}/backend:${_COMMIT_SHA}', '.']
    id: Build

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_GCP_PROJECT_ID}/backend:${_COMMIT_SHA}']
    id: Push

  # Deploy to Cloud Run (Iowa - us-central1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/${_GCP_PROJECT_ID}/backend:${_COMMIT_SHA}'
      - '--region=europe-west1'  # Iowa region
      - '--platform=managed'
      - '--allow-unauthenticated' # Public access
      - '--port=4000'
    id: Deploy
    env:
      - 'PORT=4000'

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'gcr.io/${_GCP_PROJECT_ID}/backend:${_COMMIT_SHA}'

substitutions:
  _GCP_PROJECT_ID: 'g-04-450802'
  _COMMIT_SHA: 'v2'